py_binary(
    name = "content_map",
    srcs = ["content_map.py"],
    python_version = "PY3",
    deps = [
        "//file/google_src",
        "//pyglib:gfile",
        "//third_party/py/absl:app",
        "//third_party/py/nbformat",
    ],
)

py_binary(
    name = "format_colab",
    srcs = ["format_colab.py"],
    python_version = "PY3",
    deps = [
        "//third_party/py/absl:app",
        "//third_party/py/nbformat",
    ],
)
